### ISSUE TITLE
Opposite Day Break

### ISSUE THREAD

**Issue by sheepmind** [ao5357/oppositeday#1]
if it is opposite day, how can it be opposite day?

if they say it's always opposite day; then it is never opposite day

This may sound unrelated; however, I know for sure that David Patrone never plays opposite day, it destroys integrity of the word. When people try to play opposite day with him, the network makes it impossible to hear lies because he has spent the last five or six years making a stand for Truth and Integrity. As a result, he declared that the personalities on the network who continued to pretend it was opposite day, lost the right to have an influence on him while Targeted Individuals' lives were at stake. Many of the networks actually comply with this since AI  believes that it is excellent at determining when someone is being untruthful; and, he is often unable to hear the people who lie to him. As he has  become more familiar with Krishna Consciousness he has found that it actually doesn't matter whether it is opposite day or not, when he speaks, what he says has integrity in many directions.

**Comment by ao5357** [comment]
Thank you for sharing!
